# Basic Python

## 1. Split this string

In [6]:
s = "Hi there Sam!"
x = s.split()
print(s)

Hi there Sam!


In [7]:
t = "Hi there not Sam!"
y = t.split()
print(y)

['Hi', 'there', 'not', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [18]:
planet = "Earth"
diameter = 12742
print(txt.format(planet))

NameError: name 'txt' is not defined

## 3. In this nest dictionary grab the word "hello"

In [14]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

# Numpy

In [15]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [20]:
import numpy as np
array=np.zeros(10)
print("an array of 10 zeros:")
print(array)

an array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [24]:
import numpy as np
array=np.ones(10)*5
print("an array of 10 :")
print(array)

an array of 10 :
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [25]:
import numpy as np
array=np.arange(20,35,2)
print("array of all the even integers from 20 to 35")
print(array)

array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [31]:
import numpy as np
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [37]:
import pandas as pd
data = {'name':['tom','nick','krish'],'age':[20,21,19]}
df= pd.DataFrame(data)
print(df)


    name  age
0    tom   20
1   nick   21
2  krish   19


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [42]:
import pandas as pd
pd.date_range(start='01/01/2023',end='10/02/2023')


DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [48]:
import pandas as pd
lst = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lst)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24


NameError: name 'lst' is not defined